# @package _global_

enc: "gnn_pool"

model_args:
  input_dim: 3    # x, y, d
  embedding_dim: 256
  knn: 25

  # node encoder
  node_encoder_args:
    hidden_dim: 256
    num_layers: 4
    conv_type: "GraphConv"
    activation: "gelu"
    skip: True
    norm_type: "ln"
    add_linear: False

  # center encoder
  center_encoder_args:
    hidden_dim: 256
    num_layers: 2
    pooling_type:
      - "mean"
      - "max"
    pool_comb_mode: "proj"
    meta_comb_mode: "cat"
    pre_proj: True
    post_proj: True
    attn: True
    num_heads: 4
    activation: "gelu"
    norm_type: "ln"
