# @package _global_
# model parameters

dec: "pointwise"

# POLICY model
model_args:
  decoder_type: "PointwiseDecoder"
  decoder_args:
    hidden_dim: 256
    comb_mode: "cat"
    num_layers: 2
    activation: "gelu"
    norm_type: #None

